import type { Book } from '../types/book';

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: '모던 리액트 Deep Dive',
    author: '김용찬',
    source: 'aladin',
    category: 'programming',
    publishedAt: '2025-03-10',
    coverGradient: 'linear-gradient(145deg, #667eea, #764ba2)',
    isNew: true,
  },
  {
    id: '2',
    title: '쏙쏙 들어오는 함수형 코딩',
    author: '에릭 노먼드',
    source: 'kyobo',
    category: 'programming',
    publishedAt: '2025-03-08',
    coverGradient: 'linear-gradient(145deg, #f093fb, #f5576c)',
    isNew: true,
  },
  {
    id: '3',
    title: '가상 면접 사례로 배우는 대규모 시스템 설계 기초',
    author: '알렉스 쉬',
    source: 'yes24',
    category: 'methodology',
    publishedAt: '2025-03-07',
    coverGradient: 'linear-gradient(145deg, #4facfe, #00f2fe)',
    isNew: true,
  },
  {
    id: '4',
    title: '파이썬으로 배우는 알고리즘 트레이딩',
    author: '이창민',
    source: 'aladin',
    category: 'programming',
    publishedAt: '2025-03-06',
    coverGradient: 'linear-gradient(145deg, #43e97b, #38f9d7)',
    isNew: true,
  },
  {
    id: '5',
    title: '도메인 주도 설계 철저 입문',
    author: '나루세 마사노부',
    source: 'kyobo',
    category: 'methodology',
    publishedAt: '2025-03-05',
    coverGradient: 'linear-gradient(145deg, #fa709a, #fee140)',
    isNew: true,
  },
  {
    id: '6',
    title: 'LLM을 활용한 실전 AI 애플리케이션 개발',
    author: '황성현',
    source: 'yes24',
    category: 'ai',
    publishedAt: '2025-03-05',
    coverGradient: 'linear-gradient(145deg, #a18cd1, #fbc2eb)',
    isNew: true,
  },
  {
    id: '7',
    title: 'Kubernetes 완벽 가이드',
    author: '마사야 아오야마',
    source: 'aladin',
    category: 'cloud',
    publishedAt: '2025-03-04',
    coverGradient: 'linear-gradient(145deg, #ffecd2, #fcb69f)',
    isNew: true,
  },
  {
    id: '8',
    title: '클린 코드: 애자일 소프트웨어 장인 정신',
    author: '로버트 C. 마틴',
    source: 'kyobo',
    category: 'methodology',
    publishedAt: '2025-03-03',
    coverGradient: 'linear-gradient(145deg, #2af598, #009efd)',
    isNew: true,
  },
];
